# Generated by Django 5.2.1 on 2025-06-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viaje',
            name='presupuesto_diario',
            field=models.IntegerField(),
        ),
    ]
